### ISSUE TITLE
Minimum number of connections

### ISSUE THREAD

**Issue by tbrand** [SushiCoinHQ/SushiCoin#64]
## Abstract
Currently sushid supports `--conn_max=CONN_MAX` option that decides first number of connections. The node will accept additional connections, so the name is wrong. It should be `--conn_min`. (minimum number of connections)

## AC
If a remote node is disconnected and total number of connections is less than the `--conn_min=CONN_MIN`, the node should try to find another node to be connected to guarantee the minimum number of the connections.

## Tasks
- [x] Rename `--conn_max=CONN_MAX` to `--conn_min=CONN_MIN`
- [x] Try to find another node to be connected if total number of connections is less than the specified number after some node has been disconnected.
  - [x] Add a protocol to request a node_list
